//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace priyankaApiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int Id { get; set; }
        public string AuthorName { get; set; }
        public string BookName { get; set; }
        public string AuthorImage { get; set; }
    }
}
