//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace priyankaApiProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alphabet> Alphabets { get; set; }
        public virtual DbSet<Aphorism> Aphorism { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Organ> Organs { get; set; }
        public virtual DbSet<TabletDescription> TabletDescriptions { get; set; }
        public virtual DbSet<Tablet> Tablets { get; set; }
    }
}
