//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace priyankaApiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabletDescription
    {
        public int Id { get; set; }
        public Nullable<int> Tablet_ID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> OrganID { get; set; }
    }
}
